#number of dimensions and structure points
SET,NUMBER,OF,DIMENSIONS,WITHIN,STRUCTURE
NUMBER,OF,DIMENSIONS,IS,CONSIDERED,AS,3

SET,NUMBER,OF,POINTS,WITHIN,STRUCTURE
NUMBER,OF,POINTS,IS,CONSIDERED,AS,5000

class ELUCIDIANSTRUCTURE: