class grid:
    HORIZONTAL_LINE_AMOUNT = 21 LINES
    VERTICAL_LINE_AMOUNT = 21 LINES
    DISTANCE_BETWEEN_EACH_VERTICAL_LINE = 1 INCH
    DISTANCE_BETWEEN_EACH_HORIZONTAL_LINE = 1 INCH
    VERTICAL_LINE_LENGTH = 40 INCHES
    HORIZONTAL_LINE_LENGTH = 40 INCHES
    VERTICAL_LINE_AXIS = (XAXIS)
    HORIZONTAL_LINE_AXIS = (ZAXIS)
    DIMENSIONAL_ROTATION = COUNTERCLOCKWISE

XLOCATION_AB = (1,1)
CREATE,NEW,ORIGIN,POINT,AT,LOCATION,(XLOCATION_AB(1,1))
ORIGIN,CENTER,POINT,IS,[XLOCATION(0),YLOCATION(0),ZLOCATION(0)]

class SETTING_THE_LOCATION_TO_CENTER_ORIGIN:
    SET,LOCATION,TO,CENTER,ORIGIN,LOCATION


class L:
    CREATE,NEW,DIMENSIONAL,LENGTH
    DIMENSIONAL,LENGTH,IS,CONSIDERED,input(),INCHES
    
class W:
    CREATE,NEW,DIMENSIONAL,WIDTH
    DIMENSIONAL,WIDTH,IS,CONSIDERED,input(),INCHES

class CREATE_GRID_LATTICE_VERT_HORI_LENGTH:
    CREATE,GRID,LATTICE,OF,(VERTICAL_LINE_LENGTH(40),HORIZONTAL_LINE_LENGTH(40))

class ACTIVATION_METHOD_FOR_CLASS_VECTOR:
    CLASS,VECTOR,ACTIVATION,METHOD,ACTIVATE

class MAKING_OF_VECTOR_DATA
    MAKE,VECTOR,CLASS,HORIZONTAL,METHOD,FOR,HORIZONTAL,VECTOR,VERTICE
    MAKE,VIRTUAL,DIMENSIONAL,LINE,WITHIN,XAXIS,FROM,ZERO,TO,ONEHUNDRED,PERCENT,WITH,A,TOTAL,LENGTH,OF,FOURTEEN,INCHES

class EDGELOREADHOCSYSTEM:
    #DEVCOMMANDS_ONELINERS
        class CREATE_THE_ADHOC_SYSTEM:
            CREATE,NEW,ADHOC_NETWORK
        class ALLOWING_CAPABILITY_OF_LIMITED_REACH:
            ALLOW,CAPABILITY,TO SET,A,LIMITED,REACH,UPON,DISTANCE,OF,PERSONAL,DOMAIN
        class SEARCH_FOR_NEW_ADHOC_CONNECTED_DEVICES:
            SCAN,FOR,NEW,ADHOC,DEVICES,WITHIN,EDGELORE,ADHOC_NETWORK
        class CHECK_FOR_EDGELORE_OS: 
            CHECK,EXISTING,DEVICES,THAT,ARE,CONNECTED,TO,EDGELOREADHOCSYSTEM,FOR,EDGELORE_OS
        class CHECK_EXISTING_DOMAIN_DEVICES_CONNECTED_TO_EDGELOREADHOCSYSTEM:
            CHECK,EXISTING,DEVICES,CONNECTED,TO,EDGELOREADHOCSYSTEM
        class CHECK_EXISTING_NUMBER_OF_DOMAIN_CLASSES:
            CHECK,EXISTING,TOTAL,AMOUNT,OF,DOMAIN,CLASSES,CONNECTED,TO,EDGELOREADHOCSYSTEM
        class CREATE_PRIVATE_LAN_SETTINGS: 
            CREATE,PRIVATE,LAN,SETTINGS
        class SET_EDGELORE_IPADDRESS:
            EDGELORE_IP = "102.668.421.3"
        class SET_EDGELORE_MAC_ADDRESSES:
            EDGELORE_BIGMAC = "172.4475.22.851.8.5"
            EDGELORE_LITTLEMAC = "44.31.5.2"
        
    #DEVCOMMANDS_TWOLINERS
    class CREATION_OF_DOMAIN_SETTINGS_FOR_ADHOC_SYSTEM:
        CREATE,NEW,SYSTEM,DOMAIN
        DOMAIN,IS,CONSIDERED,A,PRIVATE,PERSONAL,DOMAIN

    

