#This is a program that gives a calculates encounter ratios of individual pokemon for each season during daytime
#The program requires pandas and openpyxl to be installed via pip
from ListOfDirectoriesForAsunaAi import __FOLDER_PATH__
from ListOfDirectoriesForAsunaAi_2 import __PROGRAM_NAME__
from Pokemonarrayscript import *
from MasterScriptForte_Redone_2 import *
import pandas as pd
df = pd.read_excel (r'C:\ASUNAAI\EXTENSIONS\XLSX\TESTDATAFORPYTHONSCRIPT.xlsx', sheet_name='POKEMON000DATA')
a = df['POKEMON_NAME_LLR']
b = df['LOWERLEVELRANGE']
c = df['HIGHERLEVELRANGE']
d = df['ENCOUNTERPERCENTAGE']
e = df['TIME_OF_DAY']
f = df['SEASON_DATA']
g = df['ROUTE_NAME']
h = df['HABITAT_DEX_DATA']
print(PIDGEY,CAN,BE,FOUND,WITH,LEVELS,BETWEEN,LEVEL,df.LOWERLEVELRANGE[0],TO,LEVEL,df.HIGHERLEVELRANGE[0])
print("******************************************************************")
print("SPRING DURING DAYTIME")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[1],CHANCE,TO,FIND,PIDGEY,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[1])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[2],CHANCE,TO,FIND,SENTRET,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[1])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[2],CHANCE,TO,FIND,ZIGZAGOON,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[1])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[1],CHANCE,TO,FIND,WURMPLE,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[1])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[0],CHANCE,TO,FIND,MINUN,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[1])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[2],CHANCE,TO,FIND,LEDYBA,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[1])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[0],CHANCE,TO,FIND,ROCKRUFF,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[1])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[0],CHANCE,TO,FIND,NINCADA,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[1])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[3],CHANCE,TO,FIND,BIDOOF,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[1])
print("__________________________________________________________________")
("******************************************************************")
print ("SUMMER DURING DAYTIME")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[1],CHANCE,TO,FIND,PIKIPEK,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[2])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[1],CHANCE,TO,FIND,VULPIX,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[2])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[1],CHANCE,TO,FIND,NIDORANF,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[2])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[1],CHANCE,TO,FIND,NIDORANM,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[2])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[0],CHANCE,TO,FIND,TEDDIURSA,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[2])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[3],CHANCE,TO,FIND,SPEAROW,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[2])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[0],CHANCE,TO,FIND,DODUO,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[2])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[0],CHANCE,TO,FIND,PLUSLE,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[2])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[3],CHANCE,TO,FIND,SENTRET,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[2])
print("__________________________________________________________________")
("******************************************************************")
print ("AUTUMN DURING DAYTIME")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[2],CHANCE,TO,FIND,SENTRET,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[3])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[1],CHANCE,TO,FIND,CATERPIE,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[3])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[1],CHANCE,TO,FIND,CASCOON,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[3])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[3],CHANCE,TO,FIND,LEDYBA,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[3])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[0],CHANCE,TO,FIND,EXEGGCUTE,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[3])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[3],CHANCE,TO,FIND,NINCADA,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[3])
print("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[3],CHANCE,TO,FIND,SPEAROW,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[3])
print("__________________________________________________________________")
("******************************************************************")
print ("WINTER DURING DAYTIME")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[1],CHANCE,TO,FIND,MUNCHLAX,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[0])
("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[1],CHANCE,TO,FIND,JIGGLYPUFF,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[0])
("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[4],CHANCE,TO,FIND,ZIGZAGOON,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[0])
("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[1],CHANCE,TO,FIND,SPRITZEE,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[0])
print ("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[0],CHANCE,TO,FIND,DELIBIRD,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[0])
print ("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[1],CHANCE,TO,FIND,PSYDUCK,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[0])
print ("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[0],CHANCE,TO,FIND,GROWLITHE,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[0])
print ("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[0],CHANCE,TO,FIND,TOGEPI,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[0])
print ("__________________________________________________________________")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[3],CHANCE,TO,FIND,MAREEP,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0],WHILE,THE,"SEASON",IS,df.SEASON_DATA[0])